### ISSUE TITLE
Secrets breaks with Crystal 0.25.0 and Secrets 0.1.1

### ISSUE THREAD

**Issue by lebogan** [faustinoaq/secrets#1]
My code:
    conf["auth"] = Secrets.gets prompt: "Enter authentication phrase: " 
  
The error I get is:
...
in lib/secrets/src/secrets.cr:16:  too many block arguments (given 1, expected maximum 0)

    loop do |i|

Thanks for this way too cool shard!

**Comment by faustinoaq** [comment]
Hi @lebogan Thank you for report this issue!

Oh, looks like `loop` doesn't have a counter argument anymore :sweat_smile: 

Ref: https://github.com/crystal-lang/crystal/pull/6026

**Comment by faustinoaq** [comment]
I just released https://github.com/faustinoaq/secrets/releases/tag/v0.1.2 (backward compatible) :tada:
